fos_oauth_server:
  db_driver: orm
  client_class:        App\ApiBundle\Entity\Client
  access_token_class:  App\ApiBundle\Entity\AccessToken
  refresh_token_class: App\ApiBundle\Entity\RefreshToken
  auth_code_class:     App\ApiBundle\Entity\AuthCode
  service:
    user_provider: fos_user.user_provider.username
    options:
      access_token_lifetime: 1800   #seconds
      refresh_token_lifetime: 604800
      auth_code_lifetime: 300
