# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  param_fetcher_listener: force
  body_listener: true
  allowed_methods_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
      - { path: '^/oauth/v2/token', priorities: ['json'], fallback_format: json, prefer_extension: true }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
  serializer:
    serialize_null: true
  body_converter:
    enabled: true
  exception:
    enabled: true
    messages:
      Symfony\Component\HttpKernel\Exception\HttpException: true
      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: true